### PR TITLE
Filled rectangle border colour

### PR DESCRIPTION
**Pull request by mcgouganp**
When drawing filled rectangle, allow border to have it's own colour

### CODE REVIEW

**Comment by AndreRenaud** [comment]
Hey Paul - thanks for putting this together. The errors are because tests/main.c hasn't been updated to the new prototype for `pdf_add_filled_rectangle`. Could you change it to match?

**Comment by AndreRenaud** [comment]
Now it's complaining about the formatting (this repo is where I test a bunch of static tooling, so it's super strict on formatting). Can you run `make format`, and commit the diff? It should be just whitespace changes.

**Comment by mcgouganp** [comment]
It looks like GitHub has moved windows-latest in your build action to Window 2022 which is causing the paths for MSVC to be wrong in your workflow.

**Comment by AndreRenaud** [comment]
Thanks for spotting the workflow issue. This looks good, I'll go ahead & squash-merge it.

**Pull request merged**
