### PR TITLE
Initial support for (filled) polygons.

### PR DESCRIPTION
**Pull request by phf**
I needed to draw polygons (hexagons to be exact) and the existing lines were not good enough. The interface is intentionally simplistic since I didn't want to add another struct. There's some opportunity to refactor code as well. Also I noticed that maybe the "filled" rectangle and polygon functions should take a fill_color parameter, but for now I just followed your rectangle closely which doesn't have two color parameters. Happy to discuss how to proceed! :-)

### CODE REVIEW

**Comment by phf** [comment]
Sadly that failed test is a mystery to me since I didn't (as far as I know) change anything but a few lines of code. I did, however, notice that there are some local failures as well if I try to run the tests from the docker container. Seems to me that's in the commit I based my changes on already. :-/

**Comment by phf** [comment]
Why this is needed.
[why-polygons.pdf](https://github.com/AndreRenaud/PDFGen/files/2408215/why-polygons.pdf)

**Comment by AndreRenaud** [comment]
Hey. Thanks for this. I don't think I did a good job with the rectangle API, so there isn't a great reason to retain it. What about squashing these two functions into a single function which can optionally do the background colour, ie:
```
int pdf_add_polygon(struct pdf_doc *pdf, struct pdf_object *page, int x[],
                    int y[], int count, int border_width, uint32_t colour,
                    uint32_t bg_colour)
{
    int ret;
    struct dstr str = {0, 0, 0};

    dstr_append(&str, "BT ");
    dstr_printf(&str, "%f %f %f RG ", PDF_RGB_R(colour), PDF_RGB_G(colour),
                PDF_RGB_B(colour));
    if (!PDF_IS_TRANSPARENT(bg_colour)) 
        dstr_printf(&str, "%f %f %f rg ", PDF_RGB_R(bg_colour),
                    PDF_RGB_G(bg_colour), PDF_RGB_B(bg_colour));
    dstr_printf(&str, "%d w ", border_width);
    dstr_printf(&str, "%d %d m ", x[0], y[0]);
    for (int i = 1; i < count; i++) {
        dstr_printf(&str, "%d %d l ", x[i], y[i]);
    }
    dstr_printf(&str, "h ");
    if (PDF_IS_TRANSPARENT(bg_colour))
        dstr_printf(&str, "S ");
    else
        dstr_printf(&str, "b ");

    dstr_append(&str, "ET");

    ret = pdf_add_stream(pdf, page, str.data);
    dstr_free(&str);

    return ret;
}
```

Don't worry about the failed test. If it keeps failing after the merge I'll sort it out. The error looks a bit bogus anyway, so it's probably my fault.

**Comment by AndreRenaud** [comment]
Looks like the failing tests had something to do with scan-build. I don't really understand it well enough to investigate much further, but just jumping from clang-7 to clang-8 has resolved it. Feel free to either pull master, or just leave it and it will resolve itself in the merge.

**Comment by phf** [comment]
Sorry for the delay. Seems that now all the tests pass, thank you! :-) I don't really have an opinion on the API question you posed above, in the end neither approach is very "convenient" because we constantly have to supply the same parameters over and over again. The advantage is a simple interface, the disadvantage is having huge parameter lists. I think that an API (layer?) with some kind of "graphics context" would be better. It would allow us to configure things like color, patterns, etc. once followed by drawing all the shapes/geometry we want with those parameters. But maybe that's overthinking it? Happy to try to prototype an API like that once I get a few hours.

**Comment by AndreRenaud** [comment]
I don't mind the *var vs. struct bla, either is fine. I've pushed it in just for expediency. 

Regarding the API, changing over to having a couple of standard structs, perhaps one for general colour/thickness/background and another for font size/style and using these as the standard 'style' parameter to most of the functions might be nice. If you wanted to have a go at doing it, that would be great.

At some point I should probably stop making API changes to avoid breaking existing software, but there probably aren't enough users at this stage to worry about it, so feel free to have a go if you've got time.

Thanks

**Pull request merged**
