### PR TITLE
Bezier curves

### PR DESCRIPTION
**Pull request by endanke**
Hi @AndreRenaud

I have added some extra functions to your generator based on the PDF specification: cubic and quadratic bezier curve drawing and list based path drawing. (I've used these to generate a PDF based on the path drawing commands of an SVG.)

Feel free to review it and merge it if you find it useful!

Thanks,
Daniel

### CODE REVIEW

**Comment by AndreRenaud** [comment]
Thanks for this - do you mind running 'make format' and re-pushing it?
I'm afraid this is a repo where I try out a lot of static tooling, and the tooling is super fastidious about code formatting.

Your code also exposes a known problem in PDFGen - all the coordinates are in integers and not floats. At some point I was intending to fix this, but it would break the API entirely.

Separately, I notice that you had another branch which allowed extracting the PDF data as a string instead of to a FILE. Another way to do this would be to use open_memstream (if you're on Linux), which allows dynamic memory areas to be created and exposed as a FILE.

**Comment by endanke** [comment]
Hey and thanks for the reply!

I'll continue to work on this on Monday, will check the formatting and change back the floats to ints. I think it would be nice to have float support in the future, but I could work on that in a separate branch after this. 

About the branch with the string output: I'm using PDFGen on Android and iOS inside of a C++ library. Not sure if we have something similar to open_memstream, currently this looked like a simple solution to retrieve the raw data.

**Comment by AndreRenaud** [comment]
There is an external version of open_memstream available from https://www.piumarta.com/software/memstream/ - MIT licensed, if that makes it easier.

**Comment by endanke** [comment]
Thanks for the tip, I'm going to give it a try!

I've reverted the parameters to integers, run the formatter and also updated the documentations. It's weird because on my machine 'make docs' runs without errors, but it seems to fail on CircleCI. Do you have any idea why?

**Comment by AndreRenaud** [comment]
Thanks for this. I've squash/merged it in now.

**Pull request merged**
